server:
  port: 8080

logging.level.org.hibernate.SQL: debug


spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
